
language: java
deploy:
  provider: heroku
  api-key: $HEROKU_API_KEY
  app: marketplace-applicat

notifications:
  slack: nc-aof7593:WkeDRLH5jZfuLgskTGoTeAtW
branches:
  only:
    - master
    - develop
