import { Role } from '../_models/role';
import { User } from '../_models/user';

export const PAGE_NUM: number = 3;
export const PAGE_SIZE: number = 6;

/*export const COURIERS: Courier[] = [
  {
    id: 0,
    name: 'Name1',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: false,
  },
  {
    id: 1,
    name: 'Name2',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    id: 2,
    name: 'Name3',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    id: 3,
    name: 'Name4',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: false,
    enabled: true,
  },
  {
    id: 4,
    name: 'Name5',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    id: 5,
    name: 'Name6',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    id: 6,
    name: 'Name7',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    id: 7,
    name: 'Name8',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: false,
    enabled: true,
  },
  {
    id: 8,
    name: 'Name9',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    id: 9,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: false,
    enabled: true,
  },
  {
    id: 10,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    id: 11,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: false,
    enabled: true,
  },
  {
    id: 12,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    id: 13,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: false,
    enabled: true,
  },
  {
    id: 14,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: false,
    enabled: true,
  },
  {
    id: 15,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    id: 16,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: false,
    enabled: true,
  },
  {
    id: 17,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    id: 18,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    id: 19,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    id: 20,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
];

export const SEARCH_COURIERS: Courier[] = [
  {
    name: 'SEARCH',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    name: 'SEARCH',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    name: 'SEARCH',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
  {
    name: 'SEARCH',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: false,
    enabled: true,
  },
  {
    name: 'SEARCH',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
    active: true,
    enabled: true,
  },
];*/

export const MANAGERS: User[] = [
  {
    id: 0,
    name: 'Name1',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 1,
    name: 'Name2',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 2,
    name: 'Name3',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 3,
    name: 'Name4',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 4,
    name: 'Name5',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 5,
    name: 'Name6',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 6,
    name: 'Name7',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 7,
    name: 'Name8',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 8,
    name: 'Name9',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 9,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 10,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 11,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 12,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 13,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 14,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 15,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.Courier,
  },
  {
    id: 16,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 17,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 18,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 19,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
  {
    id: 20,
    name: 'Name',
    surname: 'Surname',
    email: 'email',
    dateOfBirth: '12.05.2000',
    phone: '123456789',
    role: Role.ProductManager,
  },
];
